name: Autocomment articfact link (atime-based regression analysis plot) on PRs

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Collect PR identifier
      run: |
        PR_SHA="${{ github.event.pull_request.head.sha }}"
        echo "PR_SHA=${PR_SHA}" >> $GITHUB_ENV
      shell: bash

    - name: setup
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("ggplot2", "devtools", "directlabels"))'

    - name: Run R script, generate plot, and push it on the PR thread as a GH-bot comment
      env: 
        repo_token: ${{ secrets.GITHUB_TOKEN }} 
      run: |
        R -e 'source("plotGenerator.r")'
        echo "![plot](./plot.png)" >> report.md
        cml comment create report.md